# Day 2 Reading Journal

This journal includes several required exercises, but it is meant to encourage active reading more generally.  You should use the journal to take detailed notes, catalog questions, and explore the content from Think Python deeply.

Reading: Think Python Chapter 6.1-6.4, 7

**Due: Monday, September 12 at 12 noon**

## [Chapter 6.1-6.4](http://www.greenteapress.com/thinkpython/html/thinkpython007.html)

Note: the exercise numbers below match up with the reading for ease of cross referencing.

**Quick check:** What is a _fruitful function_?

A fruitful function has a return value. 

In [11]:
import math
import numpy as np

### Exercise 1  
Write a `compare` function that returns `1` if `x > y`, `0` if `x == y`, and `-1` if `x < y`.

In [2]:
def compare(x,y):
    if x > y:
        return 1
    elif x == y:
        return 0
    else:
        return -1

compare(1,2)

-1

**Quick check:** Modify the `absolute_value` function so that it returns the correct result for all integer inputs.

In [3]:
def absolute_value(x):
    if x < 0:
        return -x
    if x > 0:
        return x
    if x==0:
        return x
    
absolute_value(0)

0

### Exercise 2  
Use incremental development to write a function called `hypotenuse` that returns the length of the hypotenuse of a right triangle given the lengths of the two legs as arguments. Record each stage of the development process as you go, using as many cells as you need.

In [4]:
def hypotenuse(a,b):
    length = 5
    return length

hypotenuse(1,1)

5

In [5]:
def hypotenuse(a,b):
    length = a**2+b**2
    return length

hypotenuse(3,4)

25

In [6]:
def hypotenuse(a,b):
    length = (a**2+b**2)**(1/2)
    return length

hypotenuse(3,4)

1

In [7]:
def hypotenuse(a,b):
    length = math.sqrt(a**2+b**2)
    return length

hypotenuse(3,4)

5.0

In [8]:
# I imported math

def hypotenuse(a,b):
    length = math.sqrt(a**2+b**2)
    return length

hypotenuse(3,4)

5.0

### Exercise 3  
Write a function `is_between(x, y, z)` that returns `True` if `x ≤ y ≤ z` or `False` otherwise.

In [9]:
def is_between(x,y,z):
    return x <= y and y<=z

is_between(1,2,3)

True

## [Chapter 7](http://www.greenteapress.com/thinkpython/html/thinkpython008.html)



**Quick check:** How do you test for equality in Python?

Using ==, not =

**Challenge:** Prove/disprove the Collatz conjecture :)

### Exercise 2  
Encapsulate the loop from Section 7.5 in a function called `square_root` that takes `a` as a parameter, chooses a reasonable value of `x`, and returns an estimate of the square root of `a`.

In [13]:
def square_root(a):
    if a>1:
        x = a/2 # A reasonable guess
    else:
        x = 1
    epsilon = 0.00000001
    while True:
        y = (x + a/x) / 2.0
        if abs(y-x) < epsilon:
            break
        x=y
    return x

square_root(3)

1.7320508100147274

### Exercise 3  
To test the square root algorithm you developed in Exercise 2, you could compare it with Python's `math.sqrt` function. Write a function named `test_square_root` that prints a table like this:

```python
1.0 1.0           1.0           0.0
2.0 1.41421356237 1.41421356237 2.22044604925e-16
3.0 1.73205080757 1.73205080757 0.0
4.0 2.0           2.0           0.0
5.0 2.2360679775  2.2360679775  0.0
6.0 2.44948974278 2.44948974278 0.0
7.0 2.64575131106 2.64575131106 0.0
8.0 2.82842712475 2.82842712475 4.4408920985e-16
9.0 3.0           3.0           0.0
```

The first column is a number, `a`; the second column is the square root of a computed with the function from Section 7.5; the third column is the square root computed by `math.sqrt`; the fourth column is the absolute value of the difference between the two estimates.

In [15]:
def test_square_root():
    A = np.zeros((9,4))
    x = 0
    while x<9:
        A[x,0] = x+1
        A[x,1] = square_root(x)
        A[x,2] = math.sqrt(x)
        A[x,3] = abs(A[x,2]-A[x,1])
        x = x+1
    print A
    
test_square_root()
        

[[  1.00000000e+00   1.49011612e-08   0.00000000e+00   1.49011612e-08]
 [  2.00000000e+00   1.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  3.00000000e+00   1.41421356e+00   1.41421356e+00   1.59472435e-12]
 [  4.00000000e+00   1.73205081e+00   1.73205081e+00   2.44585019e-09]
 [  5.00000000e+00   2.00000000e+00   2.00000000e+00   0.00000000e+00]
 [  6.00000000e+00   2.00000000e+00   2.23606798e+00   2.36067977e-01]
 [  7.00000000e+00   2.44948974e+00   2.44948974e+00   8.88178420e-16]
 [  8.00000000e+00   2.64575131e+00   2.64575131e+00   2.19202434e-12]
 [  9.00000000e+00   2.82842712e+00   2.82842712e+00   3.18944871e-12]]


### Challenge: Exercise 5  (optional)
The mathematician Srinivasa Ramanujan found an infinite series that can be used to generate a numerical approximation of
$\frac{1}{\pi}$:

$$\frac{1}{\pi} = \frac{2 \sqrt{2}}{9801} \sum_{k=0}^{\infty} \frac{(4k)! (1103+26390k)}{(k!)^4 396^{4k}}$$
 
Write a function called `estimate_pi` that uses this formula to compute and return an estimate of $\pi$. It should use a `while` loop to compute terms of the summation until the last term is smaller than `1e-15` (which is Python notation for $10^{−15}$). You can check the result by comparing it to `math.pi`.

[Possible solution](http://thinkpython.com/code/pi.py) (give the exercise a try before viewing the solution)

# Quick poll
About how long did you spend working on this Reading Journal?


In [17]:
2 hours

SyntaxError: invalid syntax (<ipython-input-17-e4c25cf6260c>, line 1)

## Reading Journal feedback

Have any comments on this Reading Journal? Feel free to leave them below and we'll read them when you submit your journal entry. This could include suggestions to improve the exercises, topics you'd like to see covered in class next time, or other feedback.

If you have Python questions or run into problems while completing the reading, you should post them to Slack instead so you can get a quick response before your journal is submitted.

**This was fun! I'm not quite past the point of review yet. **